"""add timestamp fields

Revision ID: 0ecdc0bc8ed6
Revises: 5d13d1da8b65
Create Date: 2020-04-23 15:47:00.205497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecdc0bc8ed6'
down_revision = '5d13d1da8b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ingredient', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('quantity_unit', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('quantity_unit', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipe', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recipe', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_ingredient', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_ingredient', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredient', 'updated_at')
    op.drop_column('recipe_ingredient', 'created_at')
    op.drop_column('recipe', 'updated_at')
    op.drop_column('recipe', 'created_at')
    op.drop_column('quantity_unit', 'updated_at')
    op.drop_column('quantity_unit', 'created_at')
    op.drop_column('ingredient', 'updated_at')
    op.drop_column('ingredient', 'created_at')
    # ### end Alembic commands ###
