"""add recipe image field

Revision ID: 5d13d1da8b65
Revises: 8850f2aeafb5
Create Date: 2020-04-23 13:57:52.526591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d13d1da8b65"
down_revision = "8850f2aeafb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("image_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "image_name")
    # ### end Alembic commands ###
