"""add recipe chef name

Revision ID: 8850f2aeafb5
Revises: c9da43bf4dcc
Create Date: 2020-04-20 12:57:40.206462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8850f2aeafb5'
down_revision = 'c9da43bf4dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('chef_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'chef_name')
    # ### end Alembic commands ###
