version: "3"
services:
  admin:
    build: ./admin
    environment:
      - ADMIN_SECRET_KEY=dYvSThPKxc1aAQok8WpjIqs/vtYioidKOx+VT5TZgIs
      - ADMIN_SQLALCHEMY_DATABASE_URL=postgresql://bareshelf:password@db/bareshelf
    ports:
      - "127.0.0.1:6001:6001"

  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=bareshelf
      - POSTGRES_DB=bareshelf
