[package]
name = "bareshelf"
version = "0.1.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

[dependencies]
tantivy = { git = "https://github.com/robyoung/tantivy", branch = "make-tweak-score-mutable-rebased" }
structopt = "0.2.10"
serde = "1.0"
log = "0.4"
