[package]
name = "bareshelf"
version = "0.1.0"
authors = ["Rob Young <rob@robyoung.digital>"]
edition = "2018"

[dependencies]
tantivy = "0.18.1"
structopt = "0.3.26"
serde = "1.0.147"
log = "0.4.17"
